FROM ruby

RUN apt-get update -y
RUN apt-get install -y git-core curl zlib1g-dev build-essential libssl-dev libreadline-dev libyaml-dev libsqlite3-dev sqlite3 libxml2-dev libxslt1-dev libcurl4-openssl-dev libffi-dev nodejs yarn

WORKDIR /usr/src/app
COPY . .
RUN bundle install --without test , development
RUN rake db:migrate

CMD [ "rails", "server" ]

